# Generated by Django 2.2 on 2020-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': '课题类别表', 'verbose_name_plural': '课题类别表'},
        ),
        migrations.AlterModelTable(
            name='projectcategory',
            table='project_category',
        ),
    ]
