# Generated by Django 2.2 on 2020-10-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201028_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('leader', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('detail', models.TextField()),
            ],
            options={
                'verbose_name': '课题信息表',
                'verbose_name_plural': '课题信息表',
                'db_table': 'project_info',
            },
        ),
        migrations.CreateModel(
            name='ProjectLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('organization', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '课题主持人表',
                'verbose_name_plural': '课题主持人表',
                'db_table': 'project_leader',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('organization', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '课题参加者表',
                'verbose_name_plural': '课题参加者表',
                'db_table': 'project_member',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '课题状态表',
                'verbose_name_plural': '课题状态表',
                'db_table': 'project_status',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
