# Generated by Django 2.2 on 2020-10-29 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201029_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='audit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
