# Generated by Django 2.2 on 2020-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201029_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectleader',
            name='addr',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='birth',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='degree',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='duty',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='education',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='major',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='national',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='province',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='tel',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='title',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='userid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectleader',
            name='zipcode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='division',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='duty',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='education',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='major',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='projectleader',
            name='organization',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='organization',
            field=models.CharField(max_length=32),
        ),
    ]
