# Generated by Django 2.2 on 2020-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201113_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('path', models.CharField(max_length=64, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '申报书附件',
                'verbose_name_plural': '申报书附件',
                'db_table': 'file_list',
            },
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='leader',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
