# Generated by Django 2.2 on 2020-11-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201114_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelist',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filelist',
            name='path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
