# Generated by Django 2.2 on 2020-11-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201117_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, null=True)),
                ('auditor', models.CharField(max_length=64, null=True)),
                ('info', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '审核信息表',
                'verbose_name_plural': '审核信息表',
                'db_table': 'audit_info',
            },
        ),
    ]
