# Generated by Django 2.2 on 2020-11-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_projectdstribute_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDstribute',
            new_name='ProjectDistribute',
        ),
    ]
