# Generated by Django 2.2 on 2020-12-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201122_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=2, null=True)),
                ('tel', models.CharField(max_length=32, null=True)),
                ('org', models.CharField(max_length=32, null=True)),
                ('birth', models.CharField(max_length=16, null=True)),
                ('addr', models.CharField(max_length=64, null=True)),
                ('img', models.CharField(max_length=256, null=True)),
                ('favour', models.TextField(null=True)),
                ('relation', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客户信息表',
                'verbose_name_plural': '客户信息表',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=32)),
                ('face_feature', models.BinaryField()),
            ],
            options={
                'verbose_name': '客户头像表',
                'verbose_name_plural': '客户头像表',
                'db_table': 'customer_face',
            },
        ),
        migrations.DeleteModel(
            name='AuditInfo',
        ),
        migrations.DeleteModel(
            name='FileList',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='ProjectDistribute',
        ),
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
        migrations.DeleteModel(
            name='ProjectLeader',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='username',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
