# Generated by Django 2.2.9 on 2020-09-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_spuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spuser',
            table='sp_user',
        ),
    ]
