# Generated by Django 2.2.9 on 2020-09-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200918_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spuser',
            options={'managed': False},
        ),
    ]
