# Generated by Django 2.2 on 2020-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_projectdstribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdstribute',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
