# Generated by Django 2.2 on 2020-11-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201122_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdistribute',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectdistribute',
            name='pid',
            field=models.CharField(default=111, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
