# Generated by Django 2.2 on 2021-01-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_duty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(help_text='研究专长', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
