# Generated by Django 2.2 on 2021-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210107_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(help_text='最后学位', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(help_text='最后学历', max_length=16, null=True),
        ),
    ]
