# Generated by Django 2.2 on 2021-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210108_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(help_text='类别名，对应父类', max_length=32)),
                ('dname', models.CharField(help_text='子类名', max_length=32)),
                ('desc', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': '课题类别子类表',
                'verbose_name_plural': '课题类别子类表',
                'db_table': 'project_category_detail',
            },
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='desc',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
