# Generated by Django 2.2 on 2021-01-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210108_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategorydetail',
            old_name='cname',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='projectcategorydetail',
            old_name='dname',
            new_name='name',
        ),
    ]
