# Generated by Django 2.2 on 2021-01-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210110_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCategoryDetail',
            new_name='ProjectCategorySon',
        ),
    ]
