# Generated by Django 2.2 on 2021-01-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210110_1112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectcategoryson',
            table='project_category_son',
        ),
    ]
