# Generated by Django 2.2 on 2021-01-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210110_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='category',
        ),
    ]
