# Generated by Django 2.2 on 2021-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210117_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDstribute',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, null=True)),
                ('pname', models.CharField(max_length=64, null=True)),
                ('assessor', models.CharField(max_length=32, null=True)),
                ('aname', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课题分配表',
                'verbose_name_plural': '课题分配表',
                'db_table': 'project_distribute',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='duty_level',
        ),
        migrations.AddField(
            model_name='user',
            name='title_level',
            field=models.CharField(help_text='职称级别', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.CharField(help_text='职务', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(help_text='职称', max_length=16, null=True),
        ),
    ]
