# Generated by Django 2.2 on 2021-01-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210117_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDstribute',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, null=True)),
                ('pname', models.CharField(max_length=64, null=True)),
                ('assessor', models.CharField(max_length=32, null=True)),
                ('aname', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课题分配表',
                'verbose_name_plural': '课题分配表',
                'db_table': 'project_distribute',
            },
        ),
    ]
