# Generated by Django 2.2 on 2021-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210117_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDstribute',
        ),
        migrations.RemoveField(
            model_name='projectdistribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectdistribute',
            name='is_active',
        ),
        migrations.AddField(
            model_name='projectdistribute',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdistribute',
            name='pid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
