# Generated by Django 2.2 on 2021-01-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_projectdistribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDistribute',
        ),
    ]
