# Generated by Django 2.2 on 2021-01-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_projectdistribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(help_text='对应user表', max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('major', models.CharField(help_text='研究方向', max_length=16, null=True)),
                ('title', models.CharField(help_text='职称', max_length=16, null=True)),
            ],
            options={
                'verbose_name': '专家信息表',
                'verbose_name_plural': '专家信息表',
                'db_table': 'assessor',
            },
        ),
        migrations.CreateModel(
            name='AssessorMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text='研究方向', max_length=16, null=True)),
            ],
            options={
                'verbose_name': '专家研究方向表',
                'verbose_name_plural': '专家研究方向表',
                'db_table': 'assessor_major',
            },
        ),
    ]
