# Generated by Django 2.2 on 2021-01-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_assessor_assessormajor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessormajor',
            old_name='major',
            new_name='name',
        ),
    ]
