# Generated by Django 2.2 on 2021-02-16 22:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_projectcategorysondirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategoryson',
            name='direction',
            field=django_mysql.models.JSONField(default=dict, help_text='课题方向列表', null=True),
        ),
    ]
