# Generated by Django 2.2 on 2021-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210218_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='未审核', help_text='注册状态，未审核、审核未通过、审核通过', max_length=10),
        ),
    ]
