# Generated by Django 2.2 on 2021-02-21 22:31

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_user_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=django_jsonfield_backport.models.JSONField(default='{"data":[{"bank":"工行","account":"123456"}]}', help_text='银行账号'),
        ),
    ]
