# Generated by Django 2.2 on 2021-02-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210221_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
    ]
