# Generated by Django 2.2 on 2021-02-21 23:47

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=django_jsonfield_backport.models.JSONField(default={'data': [{'account': ' ', 'bank': ' '}]}, help_text='银行账号'),
        ),
    ]
