# Generated by Django 2.2 on 2021-02-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20210221_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
    ]
