# Generated by Django 2.2 on 2021-02-22 00:39

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_user_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=django_jsonfield_backport.models.JSONField(default={'account': ' ', 'bank': ' '}, help_text='银行账号'),
        ),
    ]
