# Generated by Django 2.2 on 2021-02-25 15:53

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_user_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64, null=True)),
                ('pname', models.CharField(max_length=64, null=True)),
                ('assessor_result', django_jsonfield_backport.models.JSONField(null=True)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
