# Generated by Django 2.2 on 2021-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_projectassess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassess',
            options={'verbose_name': '课题评审表', 'verbose_name_plural': '课题评审表'},
        ),
        migrations.AlterField(
            model_name='projectassess',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='projectassess',
            table='project_assess',
        ),
    ]
