# Generated by Django 2.2 on 2021-03-09 16:35

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210225_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=django_jsonfield_backport.models.JSONField(help_text='角色权限包含的菜单', null=True),
        ),
    ]
