# Generated by Django 2.2.9 on 2020-09-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
