# Generated by Django 2.2.9 on 2020-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_user_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('user_email', models.CharField(max_length=32)),
                ('user_email_code', models.CharField(max_length=32)),
                ('is_active', models.CharField(max_length=4)),
                ('user_sex', models.CharField(max_length=4)),
                ('user_qq', models.CharField(max_length=32)),
                ('user_tel', models.CharField(max_length=32)),
                ('user_xueli', models.CharField(max_length=8)),
                ('user_hobby', models.CharField(max_length=32)),
                ('user_introduce', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
