# Generated by Django 2.2.9 on 2020-09-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_spuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spuser',
            options={'managed': False},
        ),
    ]
