# Generated by Django 2.2.9 on 2020-09-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200922_0702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spuser',
            table='sp_user',
        ),
    ]
